# Generated by Django 3.0.5 on 2021-06-17 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Uuser',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('role', models.CharField(max_length=10)),
                ('joining_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('Time', models.TimeField(auto_now_add=True)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('heading', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(max_length=500)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='Service.Uuser')),
            ],
        ),
        migrations.CreateModel(
            name='Requestss',
            fields=[
                ('req', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sid_id', to='Service.service')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uid_id', to='Service.Uuser')),
            ],
        ),
    ]
