# Generated by Django 3.0.5 on 2021-06-17 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='requests',
            fields=[
                ('req', models.AutoField(primary_key=True, serialize=False)),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_id', to='Service.service')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_id', to='Service.Uuser')),
            ],
        ),
    ]
